[package]
org = "ores-wasm-loaders"
name = "owls-web-loader"
version = "0.2.0"
description = "Extensible browser, worker and server WASM loading"
license = "MIT"
[package.repository]
vcs = "git"
url = "https://github.com/ores-wasm-loaders/owls-web-loader"
[dependencies]
"ores-wasm-loaders/owls-interfaces" = "=0.1.1"
[targets.repository]
dir = "."
[install]
adapter = "none"
[publish]
include_readme = true
exclude = ["tools/**", ".ores/**", ".zed/**", ".zed-pack/**", "zed_modules/**", "node_modules/**", "coverage/**"]
